In [1]:
import pandas as pd



In [2]:
# Read the data to a dataframe

cardio_df = pd.read_csv("cardio_data_cleaned.csv")
  
cardio_df.head()


Age  gender  height  weight  systolic_bp  diastolic_bp  cholesterol  \
0   51       1     171    29.0        110.0          70.0            2   
1   49       1     160    30.0        120.0          80.0            1   
2   58       1     143    30.0        103.0          61.0            2   
3   47       2     170    31.0        150.0          90.0            2   
4   42       1     146    32.0        100.0          70.0            1   

   glucose  smoker  alcohol_intake  active  cardio  
0        1       0               0       1       1  
1        1       0               0       1       1  
2        1       0               0       1       0  
3        2       0               0       1       1  
4        1       0               0       0       0

In [31]:
# Seperate our target(output) and features (input)

#Target variable
y = cardio_df["cardio"]

#Feature variables
X = cardio_df.drop(columns="cardio", axis=1)

In [32]:
X.head()

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0  64.0       1     140    60.0    130     80            1     1      0     0   
1  40.0       1     140    60.0    110     70            1     1      0     0   
2  48.0       1     140    62.0    120     80            1     1      0     0   
3  44.0       1     140    64.0    120     80            1     1      0     0   
4  40.0       1     140    68.0    100     70            1     1      0     0   

   active  
0       1  
1       1  
2       1  
3       1  
4       0

In [33]:
from collections import Counter
Counter(y)

Counter({0: 29362, 1: 31147})

In [34]:
# split the data into training, validation and testing sets. The ratio 80:10:10.
from sklearn.model_selection import train_test_split

train_size = 0.8

# First, split the dataset into training and remaining datasets

X_train, X_rem, y_train, y_rem = train_test_split(X,y, train_size=0.8)

# The validation dataset and test dataset are each 10%. So, each equal to the 50% of the remaining dataset

test_size = 0.5
valid_size= 0.5

X_valid, X_test, y_valid, y_test = train_test_split(X_rem, y_rem, test_size=0.5)

print(X_train.shape), print(y_train.shape)
print(X_valid.shape), print(y_valid.shape)
print(X_test.shape), print(y_test.shape)





(48407, 11)
(48407,)
(6051, 11)
(6051,)
(6051, 11)
(6051,)


(None, None)

In [35]:
from sklearn.preprocessing import StandardScaler

# Fitting Standard Scaler
X_scaler = StandardScaler().fit(X_train)


In [36]:
# Scaling the training data
X_train_scaled = X_scaler.transform(X_train)


In [37]:
# Create a logistic regression model

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs',
                                max_iter=200,
                                random_state=1)

In [38]:
# Train our logistic regression model

model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=200, random_state=1)

In [39]:
# Scaling the validation data
X_valid_scaled = X_scaler.transform(X_valid)

In [40]:
# Predict the model using the validation data
y_pred = model.predict(X_valid_scaled)
predictions = pd.DataFrame({"Prediction": y_pred, "Actual": y_valid}).reset_index(drop=True)
predictions.head(10)

Prediction  Actual
0           0       0
1           0       1
2           1       1
3           1       1
4           1       0
5           1       1
6           1       1
7           0       1
8           1       1
9           0       1

In [41]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_valid, y_pred))

0.7159147248388696


In [42]:
from sklearn.metrics import confusion_matrix, classification_report

matrix = confusion_matrix(y_valid, y_pred)
print(matrix)

[[2219  685]
 [1034 2113]]


In [43]:
report = classification_report(y_valid, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.68      0.76      0.72      2904
           1       0.76      0.67      0.71      3147

    accuracy                           0.72      6051
   macro avg       0.72      0.72      0.72      6051
weighted avg       0.72      0.72      0.72      6051



In [28]:
# Create Random Forest classifier

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=128, random_state=1)

In [29]:
# Train our Random forest model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [39]:
# Predict the RF model
y_pred = rf_model.predict(X_test_scaled)

In [40]:
# Put the predicted values into a dataframe
predictions = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
predictions.head(10)

Prediction  Actual
0           1       1
1           0       1
2           1       0
3           1       0
4           0       1
5           0       0
6           0       1
7           1       1
8           0       1
9           0       0

In [41]:
print(accuracy_score(y_test, y_pred))

0.7017451084082496


In [42]:
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[1255  561]
 [ 567 1399]]


In [43]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.69      0.69      0.69      1816
           1       0.71      0.71      0.71      1966

    accuracy                           0.70      3782
   macro avg       0.70      0.70      0.70      3782
weighted avg       0.70      0.70      0.70      3782



In [ ]:
>>> from sklearn import preprocessing
>>> X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.4, random_state=0)
>>> scaler = preprocessing.StandardScaler().fit(X_train)
>>> X_train_transformed = scaler.transform(X_train)
>>> clf = svm.SVC(C=1).fit(X_train_transformed, y_train)
>>> X_test_transformed = scaler.transform(X_test)
>>> clf.score(X_test_transformed, y_test)
0.93    

In [ ]:
>>> from sklearn.model_selection import cross_val_score
>>> clf = svm.SVC(kernel='linear', C=1, random_state=42)
>>> scores = cross_val_score(clf, X, y, cv=5)
>>> scores
array([0.96..., 1. , 0.96..., 0.96..., 1. ])